/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Clinic;

import static Clinic.editPatients.tmp;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author jomari
 */
public class updateMedicine extends javax.swing.JFrame {
    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    static String tmp;
    /**
     * Creates new form updateMedicine
     */
    public updateMedicine() {
        initComponents();
        conn = connection.ConnecrDb();
        this.setLocationRelativeTo(null);
        String sql2 = "select * from clinicmanagement.inventory where id =?";
        try{
            pst = conn.prepareStatement(sql2);
            pst.setString(1,tmp);
            rs = pst.executeQuery();
            if(rs.next()){
                String edit6 = rs.getString("id");
                UMidmedicine.setText(edit6);
                String edit1 = rs.getString("medicinename");
                UMmedicine.setText(edit1);
                String edit2 = rs.getString("quantity");
                UMquantity.setText(edit2);
                Date edit3 = rs.getDate("daterecieved");
                UMdateR.setDate(edit3);
                Date edit4 = rs.getDate("expirationdate");
                UMdateE.setDate(edit4);
                String edit5 = rs.getString("status");
                UMstatus.setSelectedItem(edit5);
                
  
            }
       }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"this Data is incomplete");
        }
         finally{
            try{
                rs.close();
                pst.close();   
            }
            catch(Exception e){
                
            }
        
        }
        
    
    }
    public static void setRow(String row){
        tmp = row;
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        UMmedicine = new javax.swing.JTextField();
        UMquantity = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        UMstatus = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        UMmedicineempty = new javax.swing.JLabel();
        UMquantityempty = new javax.swing.JLabel();
        UMdateRempty = new javax.swing.JLabel();
        UMdateEempty = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        UMidmedicine = new javax.swing.JTextField();
        UMdateR = new com.toedter.calendar.JDateChooser();
        UMdateE = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(87, 191, 109));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Poppins", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Clinic/addMedicineIMG/updateMedicine.png"))); // NOI18N
        jLabel1.setText("Update Medicine");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, -1, 48));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 100));

        jPanel2.setBackground(new java.awt.Color(10, 46, 54));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setBackground(new java.awt.Color(10, 46, 54));
        jLabel5.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Medicine Name");
        jLabel5.setOpaque(true);
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 160, 30));

        UMmedicine.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        UMmedicine.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        UMmedicine.setPreferredSize(new java.awt.Dimension(60, 20));
        UMmedicine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UMmedicineActionPerformed(evt);
            }
        });
        UMmedicine.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                UMmedicineKeyPressed(evt);
            }
        });
        jPanel2.add(UMmedicine, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, 190, 30));

        UMquantity.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        UMquantity.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        UMquantity.setPreferredSize(new java.awt.Dimension(60, 20));
        UMquantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UMquantityActionPerformed(evt);
            }
        });
        UMquantity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                UMquantityKeyPressed(evt);
            }
        });
        jPanel2.add(UMquantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 120, 190, 30));

        jLabel6.setBackground(new java.awt.Color(10, 46, 54));
        jLabel6.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Clinic/addMedicineIMG/addnewmedicineQuantity.png"))); // NOI18N
        jLabel6.setText("Quantity");
        jLabel6.setOpaque(true);
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 160, 30));

        jLabel7.setBackground(new java.awt.Color(10, 46, 54));
        jLabel7.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Clinic/addMedicineIMG/addnewmedicineDateR.png"))); // NOI18N
        jLabel7.setText("Date Recieved");
        jLabel7.setOpaque(true);
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 160, 30));

        jLabel8.setBackground(new java.awt.Color(10, 46, 54));
        jLabel8.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Clinic/addMedicineIMG/addnewmedicineEDate.png"))); // NOI18N
        jLabel8.setText("Expiration Date");
        jLabel8.setOpaque(true);
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 160, 30));

        jLabel11.setBackground(new java.awt.Color(10, 46, 54));
        jLabel11.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Clinic/addMedicineIMG/addnewmedicineStatus.png"))); // NOI18N
        jLabel11.setText("Status");
        jLabel11.setOpaque(true);
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, 160, 30));

        jButton4.setBackground(new java.awt.Color(237, 74, 65));
        jButton4.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Clinic/addnewpatientsimage/addnewClose.png"))); // NOI18N
        jButton4.setText("CLOSE");
        jButton4.setBorder(null);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 330, 120, 40));

        jButton5.setBackground(new java.awt.Color(87, 191, 109));
        jButton5.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Clinic/addnewpatientsimage/addnewSAVE.png"))); // NOI18N
        jButton5.setText("SAVE");
        jButton5.setBorder(null);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 330, 120, 40));

        UMstatus.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        UMstatus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Available", "Not available" }));
        UMstatus.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                UMstatusKeyPressed(evt);
            }
        });
        jPanel2.add(UMstatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 270, 190, 30));
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, 190, 10));

        UMmedicineempty.setFont(new java.awt.Font("Poppins", 2, 10)); // NOI18N
        UMmedicineempty.setForeground(new java.awt.Color(237, 74, 65));
        jPanel2.add(UMmedicineempty, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, 190, 20));

        UMquantityempty.setFont(new java.awt.Font("Poppins", 2, 10)); // NOI18N
        UMquantityempty.setForeground(new java.awt.Color(237, 74, 65));
        jPanel2.add(UMquantityempty, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 150, 190, 20));
        jPanel2.add(UMdateRempty, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, 190, 10));
        jPanel2.add(UMdateEempty, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, 190, 10));

        jLabel9.setBackground(new java.awt.Color(10, 46, 54));
        jLabel9.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("Medicine Report #");
        jLabel9.setOpaque(true);
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 160, 30));

        UMidmedicine.setEditable(false);
        UMidmedicine.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        UMidmedicine.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        UMidmedicine.setPreferredSize(new java.awt.Dimension(60, 20));
        UMidmedicine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UMidmedicineActionPerformed(evt);
            }
        });
        UMidmedicine.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                UMidmedicineKeyPressed(evt);
            }
        });
        jPanel2.add(UMidmedicine, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, 190, 30));
        jPanel2.add(UMdateR, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 170, 190, 30));
        jPanel2.add(UMdateE, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 220, 190, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 750, 400));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void UMmedicineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UMmedicineActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UMmedicineActionPerformed

    private void UMquantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UMquantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UMquantityActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
         if (UMmedicine.getText().trim().isEmpty() && UMquantity.getText().trim().isEmpty()) 
//error di makuha yung sa getdate   && AMdateR.getText().trim().isEmpty() && AMdateE.getText().trim().isEmpty()&& AMstatus.getSelectedItem().toString().isEmpty()) 
            
       {
            UMmedicineempty.setText("Medicine is empty");
            UMquantityempty.setText("Quanity name is empty");
//            AMdateRempty.setText("Date Recieved is empty");
//           AMdateEempty.setText("Date Expired is empty");
//           AMstatusempty.setText("select status is empty");

            
             } else if (UMmedicine.getText().trim().isEmpty()) {
               UMmedicineempty.setText("Medicine is empty");
            } else if (UMquantity.getText().trim().isEmpty()) {
               UMquantityempty.setText("Quantity is empty");
//           } else if (AMdateR.getJCalendar().toString().isEmpty()) {
//              AMdateRempty.setText("Date recieved is empty");
//            } else if (AMdateE.getText().trim().isEmpty()) {
//                AMdateEempty.setText("Date Expired name is empty");
//           } else if (AMstatus.getSelectedItem().toString().isEmpty()) {
//               AMstatusempty.setText("status is empty");
            }else{
            String sql=null;
        PreparedStatement pst=null;

         try{
            sql = "update clinicmanagement.inventory  set  medicinename=?, quantity=?, daterecieved=? ,expirationdate=?,status=? where id=?";
            pst = conn.prepareStatement(sql);
            
                    
               pst.setString(1, UMmedicine.getText()); 
               pst.setInt(2, Integer.parseInt(UMquantity.getText()));
               pst.setString(3, ((JTextField)UMdateR.getDateEditor().getUiComponent()).getText());
               pst.setString(4, ((JTextField)UMdateE.getDateEditor().getUiComponent()).getText());
               pst.setString(5,   UMstatus.getSelectedItem().toString());
               pst.setInt(6, Integer.parseInt(UMidmedicine.getText()));
              
               pst.executeUpdate();

           
              JOptionPane.showMessageDialog(null,"Successfully Update","Success",JOptionPane.INFORMATION_MESSAGE);
               new Inventory().update();
                pst.close();
                rs.close();
                setVisible(false);
                new Inventory().setVisible(true);
                
               
       }
       catch(Exception e)
       {
        JOptionPane.showMessageDialog(null, "MedicineName is already use");
       }     
            }
    
    }//GEN-LAST:event_jButton5ActionPerformed

    private void UMstatusKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_UMstatusKeyPressed
        
    }//GEN-LAST:event_UMstatusKeyPressed

    private void UMmedicineKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_UMmedicineKeyPressed
        UMmedicineempty.setText("");
    }//GEN-LAST:event_UMmedicineKeyPressed

    private void UMquantityKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_UMquantityKeyPressed
         UMquantityempty.setText("");
    }//GEN-LAST:event_UMquantityKeyPressed

    private void UMdateRKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_UMdateRKeyPressed
         UMdateRempty.setText("");
    }//GEN-LAST:event_UMdateRKeyPressed

    private void UMdateEKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_UMdateEKeyPressed
         UMdateEempty.setText("");
    }//GEN-LAST:event_UMdateEKeyPressed

    private void UMidmedicineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UMidmedicineActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UMidmedicineActionPerformed

    private void UMidmedicineKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_UMidmedicineKeyPressed
        UMmedicineempty.setText("");
    }//GEN-LAST:event_UMidmedicineKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(updateMedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(updateMedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(updateMedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(updateMedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new updateMedicine().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser UMdateE;
    private javax.swing.JLabel UMdateEempty;
    private com.toedter.calendar.JDateChooser UMdateR;
    private javax.swing.JLabel UMdateRempty;
    private javax.swing.JTextField UMidmedicine;
    private javax.swing.JTextField UMmedicine;
    private javax.swing.JLabel UMmedicineempty;
    private javax.swing.JTextField UMquantity;
    private javax.swing.JLabel UMquantityempty;
    private javax.swing.JComboBox UMstatus;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
