/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Clinic;

import static Clinic.viewpatientsInformation.tmp;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author jomari
 */
public class viewMedicine extends javax.swing.JFrame {
    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null; 
    static String tmp;
    public viewMedicine() {
        initComponents();
        this.setLocationRelativeTo(null);
        conn = connection.ConnecrDb();
        String sql1 = "select * from clinicmanagement.inventory where id =?";
        try{
            pst = conn.prepareStatement(sql1);
            pst.setString(1,tmp);
            rs = pst.executeQuery();
            if(rs.next()){
                String view1 = rs.getString("medicinename");
                VMmedicine.setText(view1);
                String view2 = rs.getString("quantity");
                VMquantity.setText(view2);
                String view3 = rs.getString("daterecieved");
                VMdateR.setText(view3);
                String view4 = rs.getString("expirationdate");
                VMdateE.setText(view4);
                String view5 = rs.getString("status");
                VMstatus.setText(view5);
                String view6 = rs.getString("id");
                VMidmedicine.setText(view6);
                String view7 = rs.getString("description");
                VMdescription.setText(view7);    

              
            }
       }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"this Data is incomplete");
        }
         finally{
            try{
                rs.close();
                pst.close();   
            }
            catch(Exception e){
                
            }
        
        }
        
    
    }
    public static void setRow(String row){
        tmp = row;
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        VMidmedicine = new javax.swing.JLabel();
        VMmedicine = new javax.swing.JLabel();
        VMquantity = new javax.swing.JLabel();
        VMdateR = new javax.swing.JLabel();
        VMdateE = new javax.swing.JLabel();
        VMdescription = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        AMdescriptionempty = new javax.swing.JLabel();
        VMstatus = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setSize(new java.awt.Dimension(750, 500));
        setType(java.awt.Window.Type.POPUP);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(87, 191, 109));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Poppins", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Clinic/addMedicineIMG/viewMedicine.png"))); // NOI18N
        jLabel1.setText("View Medicine");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 342, 48));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 100));

        jPanel2.setBackground(new java.awt.Color(10, 46, 54));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setBackground(new java.awt.Color(10, 46, 54));
        jLabel5.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Medicine Name:");
        jLabel5.setOpaque(true);
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 130, 30));

        jLabel6.setBackground(new java.awt.Color(10, 46, 54));
        jLabel6.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Clinic/addMedicineIMG/addnewmedicineQuantity.png"))); // NOI18N
        jLabel6.setText("Quantity:");
        jLabel6.setOpaque(true);
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 130, 30));

        jLabel7.setBackground(new java.awt.Color(10, 46, 54));
        jLabel7.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Clinic/addMedicineIMG/addnewmedicineDateR.png"))); // NOI18N
        jLabel7.setText("Date Recieved:");
        jLabel7.setOpaque(true);
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 130, 30));

        jLabel8.setBackground(new java.awt.Color(10, 46, 54));
        jLabel8.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Clinic/addMedicineIMG/addnewmedicineEDate.png"))); // NOI18N
        jLabel8.setText("Expiration Date:");
        jLabel8.setOpaque(true);
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 130, 30));

        jLabel11.setBackground(new java.awt.Color(10, 46, 54));
        jLabel11.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Clinic/addMedicineIMG/addnewmedicineStatus.png"))); // NOI18N
        jLabel11.setText("Status:");
        jLabel11.setOpaque(true);
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, 130, 30));

        jLabel9.setBackground(new java.awt.Color(10, 46, 54));
        jLabel9.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("Medicine Report #");
        jLabel9.setOpaque(true);
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 130, 30));

        jButton4.setBackground(new java.awt.Color(237, 74, 65));
        jButton4.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Clinic/addnewpatientsimage/addnewClose.png"))); // NOI18N
        jButton4.setText("CLOSE");
        jButton4.setBorder(null);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 370, 130, 40));

        VMidmedicine.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        VMidmedicine.setForeground(new java.awt.Color(255, 255, 255));
        VMidmedicine.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel2.add(VMidmedicine, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 190, 30));

        VMmedicine.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        VMmedicine.setForeground(new java.awt.Color(255, 255, 255));
        VMmedicine.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel2.add(VMmedicine, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 70, 190, 30));

        VMquantity.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        VMquantity.setForeground(new java.awt.Color(255, 255, 255));
        VMquantity.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel2.add(VMquantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 120, 190, 30));

        VMdateR.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        VMdateR.setForeground(new java.awt.Color(255, 255, 255));
        VMdateR.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel2.add(VMdateR, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 170, 190, 30));

        VMdateE.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        VMdateE.setForeground(new java.awt.Color(255, 255, 255));
        VMdateE.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel2.add(VMdateE, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 220, 190, 30));

        VMdescription.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        VMdescription.setForeground(new java.awt.Color(255, 255, 255));
        VMdescription.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel2.add(VMdescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 320, 190, 30));

        jLabel10.setBackground(new java.awt.Color(10, 46, 54));
        jLabel10.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Clinic/addnewpatientsimage/addnewSTUDID.png"))); // NOI18N
        jLabel10.setText("Description");
        jLabel10.setOpaque(true);
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 320, 130, 30));

        AMdescriptionempty.setFont(new java.awt.Font("Poppins", 2, 10)); // NOI18N
        AMdescriptionempty.setForeground(new java.awt.Color(237, 74, 65));
        jPanel2.add(AMdescriptionempty, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 350, 190, 20));

        VMstatus.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        VMstatus.setForeground(new java.awt.Color(255, 255, 255));
        VMstatus.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel2.add(VMstatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 270, 190, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 750, 430));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
         Inventory viewP = new Inventory();
         viewP.setVisible(true);
         setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewMedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewMedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewMedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewMedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewMedicine().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AMdescriptionempty;
    private javax.swing.JLabel VMdateE;
    private javax.swing.JLabel VMdateR;
    private javax.swing.JLabel VMdescription;
    private javax.swing.JLabel VMidmedicine;
    private javax.swing.JLabel VMmedicine;
    private javax.swing.JLabel VMquantity;
    private javax.swing.JLabel VMstatus;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
